url: "https://www.joshminkus.com"
baseurl: ""
title: "Josh Minkus" 
permalink: pretty

collections: 
  artworks:
    output: true
    permalink: /art/:path/
  texts:
    output: true
    permalink: /texts/:path/

defaults:
  - scope:
      path: ""
      type: "artworks"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "texts"
    values:
      layout: "default"