url: "https://www.joshminkus.com"
baseurl: ""
title: "Josh Minkus" 
permalink: pretty

collections: 
  artworks:
    output: true
    permalink: /art/:path/
  writings:
    output: true
    permalink: /writing/:path/

defaults:
  - scope:
      path: ""
      type: "artworks"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "writings"
    values:
      layout: "default"